CREATE TABLE [dbo].[Books]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [Title] NVARCHAR(MAX) NOT NULL, 
    [Author] INT FOREIGN KEY REFERENCES Authors([Id]) NULL, 
	[Genre] INT FOREIGN KEY REFERENCES Genres([Id]) NULL,
    [Pages] INT NULL
)
